"""empty message

Revision ID: 402dacb7cd54
Revises: a3b7e86f2b98
Create Date: 2024-02-26 22:16:26.762623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402dacb7cd54'
down_revision = 'a3b7e86f2b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=80), nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residente', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
