"""empty message

Revision ID: 710aa75a29eb
Revises: 44d5bd7f6b07
Create Date: 2024-02-21 01:12:32.187342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710aa75a29eb'
down_revision = '44d5bd7f6b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_residencial_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'unidad_residencial', ['unidad_residencial_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unidad_residencial_id')

    # ### end Alembic commands ###
