"""empty message

Revision ID: 712f656c8fa7
Revises: 710aa75a29eb
Create Date: 2024-02-21 20:47:49.972408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712f656c8fa7'
down_revision = '710aa75a29eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.drop_constraint('publicaciones_residente_id_fkey', type_='foreignkey')
        batch_op.drop_column('residente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('publicaciones_residente_id_fkey', 'residentes', ['residente_id'], ['id'])

    # ### end Alembic commands ###
